/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM */

#ifndef _Included_org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM
#define _Included_org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM
#ifdef __cplusplus
extern "C" {
#endif
#undef org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM_BASE_QUALITY_SCORE_THRESHOLD
#define org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM_BASE_QUALITY_SCORE_THRESHOLD 18L
/*
 * Class:     org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM
 * Method:    initFPGA
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM_initFPGA
  (JNIEnv *, jobject);

/*
 * Class:     org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM
 * Method:    doneFPGA
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM_doneFPGA
  (JNIEnv *, jobject);

/*
 * Class:     org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM
 * Method:    pushData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM_pushData
  (JNIEnv *, jobject, jbyteArray);


/*
 * Class:     org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM
 * Method:    popData
 * Signature: ([B)V
 */
JNIEXPORT jbyteArray JNICALL Java_org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM_popData
  (JNIEnv *, jobject);

/*
 * Class:     org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM
 * Method:    resiveFromFPGA
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_broadinstitute_gatk_utils_pairhmm_FPGAPairHMM_resiveFromFPGA
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif